### ISSUE TITLE
Form Element :: Checkbox :: Clicking checkboxes gives inconsistent behavior

### ISSUE THREAD

**Issue by peter-tell** [Pageworks/papertrain#138]
Clicking on a Checkbbox in Chrome on OSX doesn't respond the same with every click. Sometimes it triggers the action, and a second click will actually check the box, other times it highlight everything within the Fields.

Expected Behavior:
Clicking a checkbox or checkbox label toggles the input consistently and nothing else.

**Comment by codewithkyle** [comment]
Same issue as #137
